version: "3"

services:
  joomla:
    image: p2718na/joomla
    deploy:
      restart_policy:
        condition: on-failure
    ports:
    - "8080:80"

  db:
    image: mysql:5.7
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
      MYSQL_DATABASE: joomla
    volumes:
    - ./mysql-data:/var/lib/mysql