version: "3"

services:
  joomla:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    volumes:
      - ./state/images:/var/www/html/joomla/images
      - ./state/logs:/var/log/nginx
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_DATABASE: joomla
      SITE_NAME: test

  db:
    image: mysql:5.7
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: joomla
      MYSQL_USER: joomla
      MYSQL_PASSWORD: joomla
      MYSQL_DATABASE: joomla
    volumes:
      - ./state/mysql-data:/var/lib/mysql