version: "3"

services:
  joomla:
    image: joomla
    deploy:
      restart_policy:
        condition: on-failure
    ports:
    - "8080:80"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_USER: root
      JOOMLA_DB_PASSWORD: password
    networks:
      - webnet

  joomladb:
    image: mysql:5.7
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./mysql-data:/var/lib/mysql
    networks:
    - webnet

networks:
  webnet: